-- Disable Row Level Security for all tables temporarily
-- Run this in your Supabase SQL Editor

-- Disable RLS on all main tables
ALTER TABLE "Users" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Customers" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Supplier" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Warehouses" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Inventory" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryLog" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderDetail" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Shipments" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ShippingCarrier" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseOrder" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Production" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentCustomer" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentSupplier" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Returns" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderStatusHistory" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseOrderStatusHistory" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ReturnStatusHistory" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductionStatusLog" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SupplierPerformance" DISABLE ROW LEVEL SECURITY;

-- Drop any existing policies
DROP POLICY IF EXISTS "Users can view their own data" ON "Users";
DROP POLICY IF EXISTS "Users can update their own data" ON "Users";

SELECT 'RLS disabled on all tables!' as message;
